# Generated by Django 3.0.6 on 2020-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0004_invoices_medicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='username',
            field=models.CharField(default='aryan', max_length=100),
            preserve_default=False,
        ),
    ]
